name: CI Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore PaperMania/Server/Server.csproj

      - name: Build project
        run: dotnet build PaperMania/Server/Server.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test PaperMania/Server/Server.csproj --no-build --configuration Release
