name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show repo files
        run: ls -R

      - name: Show files in PaperMania directory
        run: ls -R PaperMania

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: PaperMania
        run: dotnet restore PaperMania.sln

      - name: Build solution
        working-directory: PaperMania
        run: dotnet build PaperMania.sln --no-restore --configuration Release

      - name: Run tests
        working-directory: PaperMania
        run: dotnet test PaperMania.sln --no-build --verbosity normal --configuration Release
