name: Deploy to Server

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/paper-mania-server:latest -f PaperMania/Server/Dockerfile PaperMania/Server

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/paper-mania-server:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/paper-mania-server:latest
          docker stop paper-mania-server || true
          docker rm paper-mania-server || true
          docker run -d \
            --name paper-mania-server \
            --network paper-mania-net \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USERNAME }}/paper-mania-server:latest
